/**
  we want `read-committed` as the default txn isolation level on our databases
  - its _required_ to support high concurrency operations for the upserts generated by `sql-schema-generator`
  - this is done automatically by sql-schema-control under the cicd user
*/
ALTER DATABASE @declapract{variable.databaseName} SET DEFAULT_TRANSACTION_ISOLATION TO 'read committed';
