ignores:
  - "@src/*"
  - "@src/.*"
  - rhachet
  - declapract
  - declapract-typescript-ehmpathy
  - "@commitlint/config-conventional"
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - husky
  - tsx
  - tsc-alias
  - yaml
ignorePatterns:
  - src/practices/lint/bad-practices/*
