ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - '@trivago/prettier-plugin-sort-imports'
  - '@tsconfig/node-lts-strictest'
  - serverless-prune-plugin
  - core-js
  - ts-jest
  - ts-node
  - date-fns
  - test-fns
  - husky
  - if-env
  - '@ehmpathy/as-command'
  - helpful-errors
  - visualogic
