name: provision

on:
  push:
    tags:
      - v*
    branches:
      - 'main'
      - 'master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # per [workflow] x [branch, tag]
  cancel-in-progress: true #  cancel workflows for non-latest commits

jobs:
  github:
    uses: ./.github/workflows/.terraform.yml
    with:
      working-directory: provision/github/environment
      github-environment: prod
      aws-region: us-east-1
      aws-account-id: '@declapract{variable.awsAccountId.prod}'
    secrets:
      aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      github-token: ${{ secrets.PROVISION_GITHUB_GITHUB_TOKEN }}
