name: deploy-prod-on-tag

on:
  push:
    tags:
      - v*

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: install
        run: npm install

      # test in dev env
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials.outputs.aws-account-id}} != '@declapract{variable.awsAccountId.dev}' ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: provision:integration-test-db
        run: npm run provision:integration-test-db

      - name: test
        run: npm run test

      # deploy in prod env
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials.outputs.aws-account-id}} != '@declapract{variable.awsAccountId.prod}' ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: deploy
        run: DEPLOYER_NAME=$GITHUB_ACTOR npm run deploy:prod

      - name: test:acceptance
        run: SERVERLESS_STAGE=prod npm run test:acceptance
