name: deploy-prod-on-tag

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need all commits to test:commits

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
          cache: 'npm'

      - name: install
        run: npm ci

      # test in dev env
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials-dev
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials-dev.outputs.aws-account-id}} != '@declapract{variable.awsAccountId.dev}' ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: provision:integration-test-db
        run: npm run provision:integration-test-db

      - name: test
        run: npm run test

      # deploy in prod env
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials-prod
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials-prod.outputs.aws-account-id}} != '@declapract{variable.awsAccountId.prod}' ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: deploy
        run: DEPLOYER_NAME=$GITHUB_ACTOR npm run deploy:prod

      - name: test:acceptance
        run: STAGE=prod npm run test:acceptance
