import { FileCheckType, FileFixFunction } from 'declapract';

export const check = FileCheckType.CONTAINS;

export const fix: FileFixFunction = (contents) => {
  if (!contents) return {};
  return {
    contents: contents
      .replace(
        `import { deepOmit } from '../../../__nonpublished_modules__/deep-omit';`,
        `import { omitAutogeneratedValues } from 'domain-objects';`,
      )
      .replace(
        /deepOmit\(([\w|!|?|\.]+), \[[\w'", ]+\]\)/g,
        'omitAutogeneratedValues($1)',
      ),
  };
};
