name: .publish-npm

on:
  workflow_call:
    secrets:
      npm-auth-token:
        required: true
        description: required credentials to authenticate with the aws account under which to publish

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: install
        run: npm ci

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
