name: publish

on:
  push:
    tags:
      - v*

jobs:
  test:
    uses: ./.github/workflows/.test.yml
    with:
      aws-region: us-east-1
      aws-account-id: '@declapract{variable.awsAccountId.dev}'
    secrets:
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

  publish:
    uses: ./.github/workflows/.publish-npm.yml
    secrets:
      npm-auth-token: ${{ secrets.NPM_TOKEN }}
