name: .test

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        description: the aws region within which we should run the tests
        required: true
      aws-account-id:
        type: string
        description: the id of the account the credentials are expected to access
        required: true
    secrets:
      aws-access-key-id:
        required: true
        description: required credentials to authenticate with aws the aws account against which to run the tests
      aws-secret-access-key:
        required: true
        description: required credentials to authenticate with aws the aws account against which to run the tests

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: install
        run: npm ci --ignore-scripts

      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

  # run tests in parallel
  test-commits:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need all commits to test:commits

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:commits
        run: npm run test:commits

  test-types:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:types
        run: npm run test:types

  test-format:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:format
        run: npm run test:format

  test-lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:lint
        run: npm run test:lint

  test-unit:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: test:unit
        run: npm run test:unit

  test-integration:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials.outputs.aws-account-id}} != ${{ inputs.aws-account-id }} ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: provision:integration-test-db
        run: npm run provision:integration-test-db

      - name: test:integration
        run: npm run test:integration

  test-acceptance-locally:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: read nvmrc
        id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: set node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvmrc.outputs.NODE_VERSION }}

      - name: grab node_modules from cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: credentials
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1

      - name: confirm aws credentials
        run: |
          [[ ${{steps.credentials.outputs.aws-account-id}} != ${{ inputs.aws-account-id }} ]] \
            && echo 'wrong aws account' && exit 1 \
            || echo 'correct aws account';

      - name: provision:integration-test-db
        run: npm run provision:integration-test-db

      - name: test:acceptance:locally
        run: npm run test:acceptance:locally
