name: test

on:
  workflow_call:
  push:
    branches-ignore:
      - 'main' # exclude main branch, since deploy workflow triggers on main, and calls the test workflow inside of it already
    tags-ignore:
      - v* # exclude tags, since deploy workflow triggers on tags, and calls the test workflow inside of it already

jobs:
  suite:
    uses: ./.github/workflows/.test.yml
    with:
      aws-region: us-east-1
      aws-account-id: '@declapract{variable.awsAccountId.dev}'
    secrets:
      aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
