import type { FileCheckFunction, FileFixFunction } from 'declapract';
import expect from 'expect';

import { defineExpectedGitignoreContents } from '../../../utils/defineExpectedGitignoreContents';

/**
 * .what = the ignores this practice declares — the build output an expo app emits
 * .why  = `android/` and `ios/` are generated by `expo prebuild`, so they are scratch
 *         in a managed-workflow repo.
 * .note = this list is NOT sorted here, and that is deliberate.
 *         `defineExpectedGitignoreContents` sorts the union of these lines with the
 *         repo's own, so a `.sort()` at this site would be a second sort that changes
 *         no output -- while it mutates a module-cached array in place. `readonly`
 *         forbids that mutation outright.
 */
const ignoresSortable: readonly string[] = ['android/', 'ios/'];

export const check: FileCheckFunction = (contents) => {
  expect(contents).toEqual(
    defineExpectedGitignoreContents({ contents, ignoresSortable }),
  );
};

export const fix: FileFixFunction = (contents) => {
  return {
    contents: defineExpectedGitignoreContents({ contents, ignoresSortable }),
  };
};
