ignores:
  - "@src/*"
  - "@src/.*"
  - rhachet
  - rhachet-brains-anthropic
  - rhachet-brains-fireworksai
  - rhachet-brains-xai
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - rhachet-roles-rhachet
  - declapract
  - declapract-typescript-ehmpathy
  - "@commitlint/config-conventional"
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - husky
  - tsx
  - tsc-alias
  - yalc
  - test-fns
  - type-fns
