ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - '@commitlint/config-conventional'
  - '@trivago/prettier-plugin-sort-imports'
  - '@tsconfig/node-lts-strictest'
  - core-js
  - ts-jest
  - ts-node
  - test-fns
  - '@ehmpathy/error-fns'
  - husky
  - if-env
